kind: state_and_parameter
num_steps: 2
alpha: ${.num_steps}
num_assimilation_windows: 5
seed: 42
obs_error_std: 0.25
init_conditions_dir: esmda_init_conditions
true_sim_id: 0
use_init_conditions: false

smoother:
  _target_: data_assimilation.smoothing.esmda.StateAndParameterESMDA
  num_steps: ${..num_steps}
  alpha: ${..alpha}
