name: pylbm
solver_name: pylbm
compile: true

forward_model:
  _target_: pylbm.forward_model.ForwardModel
  _convert_: all
  stl_path: examples/lbm/experiments/xie_castro_2008_STL.stl
  experiment_name: runcase
  cuda: false
  verbose: false
  boundary_condition: inflow_outflow
  nx: ${domain.nx}
  ny: ${domain.ny}
  nz: ${domain.nz}
  bounds: ${domain.bounds}
  simulation_time: ${time.simulation_time}
  output_frequency: ${time.output_frequency}
  spinup_time: ${time.spinup_time}

prepare:
  _target_: pyurbanair.config.hydra_helpers.prepare_compile
  compile: ${..compile}

ensemble_model:
  _target_: pylbm.ensemble_forward_model.EnsembleForwardModel
  _convert_: all
  ensemble_size: ${ensemble.ensemble_size}
  num_parallel_processes: ${ensemble.num_parallel_processes}
  num_cpus_per_process: ${ensemble.num_cpus_per_process}
