"""Generate ``figures/NOTES.md`` documenting the assumptions behind the figures.

Mirrors the checklist in ``docs/figure_specs.md`` §10 and records the concrete
state of the data (which runs are present/missing, resolutions, sensor coords,
the canonical-truth remap, the PALM nz handling, etc.).
"""
from __future__ import annotations

import argparse
import pathlib
import sys

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent))

from figspec import dataio
from figspec import figcommon as FC
from figspec import mask


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", type=pathlib.Path,
                    default=pathlib.Path(__file__).resolve().parent.parent / "figures")
    args = ap.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    a = dataio.discover_block_a()
    b = dataio.discover_block_b()
    g = dataio.truth_grid()
    solid = mask.truth_solid_mask()
    zi = mask.nearest_z_index(FC.PED_Z)

    # sensor coords from a representative complete run
    rep = next((r for r in a if r.model == "udales" and r.complete), a[0])
    cfg = dataio.load_config(rep)
    assim = dataio.sensor_coords(cfg, "assimilation")
    val = dataio.sensor_coords(cfg, "validation")

    def res_list(model):
        rs = sorted([r for r in a if r.model == model], key=lambda r: r.nx)
        return ", ".join(f"{r.res_label} ({r.res_label_dx}{'' if r.complete else ', INCOMPLETE'})"
                         for r in rs)

    L = []
    L.append("# figures/NOTES.md — assumptions & data state\n")
    L.append("_Auto-generated by `scripts/make_notes.py`. Reconcile against "
             "`docs/figure_specs.md` §10._\n")

    L.append("## Truth (canonical)\n")
    L.append(f"- All blocks compare against the **wide uDALES ground truth**: "
             f"`{dataio.TRUTH_STATE}`.\n")
    L.append("- The per-run `truth_access.yaml` paths are **stale** (runs were "
             "produced on several systems incl. DelftBlue); they are ignored and "
             "remapped to the canonical truth above (confirmed by the user).\n")
    L.append(f"- Common evaluation grid = truth grid: z-levels {list(g['z'].astype(float))}, "
             f"y∈[{g['y'].min():.1f},{g['y'].max():.1f}] (n={len(g['y'])}), "
             f"x∈[{g['x'].min():.1f},{g['x'].max():.1f}] (n={len(g['x'])}), Δx=1 m.\n")
    L.append("- The finest uDALES assimilation run shares the truth grid "
             "(inverse-crime caveat) — all metrics are nonetheless computed on the "
             "common grid by interpolation, so cross-model numbers stay comparable.\n")

    L.append("\n## 1. Parameters present\n")
    L.append("- Only **`inflow_angle` [deg]** and **`velocity_magnitude` [m/s]** are "
             "stored for every model. **`pressure_gradient` is NOT on disk** for any "
             "run, so it is omitted from all parameter panels/tables.\n")

    L.append("\n## 2. Resolutions per model\n")
    for m in ("palm", "udales", "lbm"):
        L.append(f"- **{m}**: {res_list(m)}\n")
    L.append("- **Representative / finest** resolution used in A1-grid, A3, "
             "animations: the finest **complete** run per model (nx60, Δx=1 m).\n")
    L.append("- **PALM nz handling:** PALM runs use nz32 (33 vertical levels, "
             "z 0.5..32.5 m); the others use nz16. PALM fields are interpolated onto "
             "the truth's 16 physical z-levels, so PALM is treated as nz16 as "
             "requested — the discrepancy does not affect the figures.\n")
    L.append("- **Missing run:** `pypalm_nx45_ny60_nz16` was never produced; only "
             "`pypalm_nx45_ny60_nz32` exists (and is treated as nz16). Any run still "
             "lacking `posterior_state_mean.nc`/`run_summary.yaml` is skipped and "
             "listed below; re-run the figures once it finishes.\n")
    incomplete = [r.name for r in (a + b) if not r.complete]
    L.append(f"- **Currently incomplete (skipped):** "
             f"{incomplete if incomplete else 'none — all discovered runs complete'}.\n")

    L.append("\n## 4. Sensors\n")
    L.append(f"- **Assimilation sensors ({0 if assim is None else len(assim)}):** "
             f"{[tuple(map(float, p)) for p in assim] if assim is not None else 'n/a'} (x,y,z).\n")
    L.append(f"- **Held-out validation sensors ({0 if val is None else len(val)}):** "
             f"{[tuple(map(float, p)) for p in val] if val is not None else 'n/a'} (x,y,z) — "
             "deeper in the canopy/wake, never assimilated; used in A4/B4 and "
             "validation-sensor RMSE columns.\n")

    L.append("\n## 5. Evaluation slice & building mask\n")
    L.append(f"- Field figures use the **pedestrian-height** slice nearest z={FC.PED_Z:.0f} m "
             f"(truth z-level index {zi}, z={float(g['z'][zi]):.0f} m).\n")
    if solid is None:
        L.append("- **Building mask: NONE** (STL not found) — field metrics run over "
                 "all cells. Document this if buildings should be excluded.\n")
    else:
        frac = float(solid.mean())
        frac2d = float(solid[zi].mean())
        L.append(f"- **Building mask** voxelized from the Xie & Castro (2008) STL "
                 f"(`{dataio.STL_PATH.name}`) onto the truth grid: {frac:.1%} of cells "
                 f"solid overall, {frac2d:.1%} on the pedestrian slice. Solid cells are "
                 "excluded from field RMSE and hatched in heatmaps.\n")

    L.append("\n## 6. Horizons / windows\n")
    ea = dataio.window_edges(rep)
    L.append(f"- **Block A (param-only):** 6 windows × 180 s = **1080 s** horizon "
             f"(edges {None if ea is None else [round(float(x)) for x in ea]}).\n")
    repb = next((r for r in b if r.complete), None)
    eb = dataio.window_edges(repb) if repb else None
    L.append(f"- **Block B/C (state):** 10 windows × 30 s = **300 s** horizon "
             f"(edges {None if eb is None else [round(float(x)) for x in eb]}).\n")
    L.append("- **Overlapping horizon for the A-vs-B baseline:** 0..300 s. The "
             "param-only baseline in Block B is the finest uDALES Block-A run "
             "restricted to 0..300 s.\n")

    L.append("\n## 7. Cost numbers\n")
    L.append("- Wall-times **are** available (`run_summary.yaml timing."
             "esmda_total_seconds` / `mean_window_seconds`) and are used as the cost "
             "axis in S1 and Table B-I. N_e and #forward runs "
             "(=N_e·N_win·(N_steps+1)) are available as alternates.\n")

    L.append("\n## 8. Units & sign conventions\n")
    L.append("- Angles in **degrees**, speed in **m/s**. Difference maps use "
             "**error = model − truth** with a symmetric diverging scale centred at 0.\n")

    L.append("\n## Method labels (verbatim, spec §1)\n")
    L.append("- `param-only`, `IC+param (corr)`, `IC+param (dist)`, "
             "`IC+param (reduction)`, `IC+state+param (reduction)`.\n")
    L.append("- Block B folder→method map: `localization_corr_ic`→IC+param (corr); "
             "`localization_dist_dist_ic`→IC+param (dist); `svd_ic`→IC+param "
             "(reduction); `svd_all`→IC+state+param (reduction).\n")

    L.append("\n## Caveats to interpret on the slides\n")
    L.append("- On the short 0..300 s horizon, early results show the **param-only "
             "baseline can match or beat** the IC/state-estimation methods on |U| "
             "field RMSE; among the state methods, `IC+state+param (reduction)` is "
             "the strongest. Worth a sentence on the slide — the short window + "
             "localization noise likely limit the state-update benefit. Verify "
             "against the regenerated B2/Table B-I numbers.\n")

    path = args.out / "NOTES.md"
    path.write_text("".join(L))
    print(f"  + {path}")


if __name__ == "__main__":
    main()
