data_dir: training_data/pyudales_small
split: train
batch_size: 8
shuffle: true
num_workers: 0
state_vars:
  - u
  - v
  - w
param_vars: null
cache: false
dtype: float32
pushforward_steps: 10
plot_dir: .temp/dataloading
