# @package _global_

defaults:
  - /neural_surrogate_architectures/upt@architecture: small
  - _self_

model_name: upt_small

trainer:
  _target_: neural_surrogates.Trainer
  num_epochs: 500
  device: cuda
  patience: 25

optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-3
  weight_decay: 1.0e-6

loss:
  _target_: torch.nn.MSELoss

dataset:
  _target_: neural_surrogates.TransitionDataset
  root_dir: training_data/pyudales_small
  state_vars:
    - u
    - v
    - w
  param_vars: null
  cache: false
  dtype: float32
  pushforward_steps: 5

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 64
  shuffle: true
  num_workers: 0
