kernel_size: 3

trainer:
  _target_: neural_surrogates.Trainer
  num_epochs: 5
  device: cpu

optimizer:
  _target_: torch.optim.Adam
  lr: 1.0e-3

loss:
  _target_: torch.nn.MSELoss

dataset:
  _target_: neural_surrogates.TransitionDataset
  root_dir: training_data/pylbm_tiny
  state_vars:
    - u
    - v
    - w
  param_vars: null
  cache: false
  dtype: float32

dataloader:
  _target_: torch.utils.data.DataLoader
  batch_size: 8
  shuffle: true
  num_workers: 0

