num_time_points: 3
method: gp_linear_trend
method_kwargs:
  correlation_length: 10.0
  slope_damping_time: null
truth_method: gp_linear_trend
truth_method_kwargs:
  correlation_length: 100.0

prior_model:
  _target_: pyurbanair.parameter_time_series.build_parameter_time_series
  _convert_: all
  method: ${time_varying.method}
  external_priors: ${params.external}
  ensemble_size: ${ensemble.ensemble_size}
  method_kwargs: ${time_varying.method_kwargs}

