"""
Per-run LBM build tree.

The Fortran solver bakes its grid dimensions in at compile time, so this wrapper
has to rewrite ``mod_dimensions.F90`` and ``m_solid_objects_init.F90`` for every
experiment, and the makefile's own rules rewrite ``depends.file`` /
``source.files`` on every build. All four are files *tracked* by the LBM
submodule. Editing them in place meant:

* ``git status`` in the parent repo permanently showed ``M libs/pylbm/LBM``, and
  that dirty gitlink was repeatedly swept into unrelated commits (it broke CI);
* two runs with different grids raced on a single shared source tree;
* the ``bin/boltzmann`` left behind carried whichever dimensions were baked in
  last, so a later run could silently pick up a binary built for another grid.

So the submodule is treated as read-only and every run builds in a private copy
of the tree under its own scratch directory. ``materialize_build_tree`` mirrors
``src/`` and the ``bin/`` helper scripts into that copy; the makefile's
``../build`` and ``../bin`` relative paths keep working because the copy has the
same layout. The submodule stays byte-identical to its checked-out commit.

``PYLBM_LBM_PATH`` still bypasses all of this: that copy is managed by the
caller (e.g. rsynced onto node-local scratch by a batch job), so it is used in
place and never mirrored.
"""

import hashlib
import json
import logging
import os
import pathlib
import shutil
from typing import Any, Optional, Union

logger = logging.getLogger(__name__)

# Everything in ``src/`` is mirrored except build output, so the copy cannot go
# wrong by omission -- the makefile pulls in more than the Fortran sources
# (``target.mk`` defines TARGET, ``source.files``/``depends.file`` are included).
# A deny-list of generated artifacts is the safe direction here: missing one of
# those merely leaves a stale file in scratch, whereas missing a *source* breaks
# the build in obscure ways (an empty TARGET silently turns `make install` into
# `cp ../build/ <bindir>`).
_GENERATED_SUFFIXES = (".o", ".mod", ".a", ".bak", ".old", ".smod")
_GENERATED_NAMES = ("tags", ".DS_Store")

# Helper scripts the makefile shells out to (``../bin/mkdepend.pl`` and friends).
_BIN_SUFFIXES = (".pl", ".sh")

BUILD_STAMP_NAME = ".pylbm_build_stamp.json"


def _is_mirrored(path: pathlib.Path) -> bool:
    """Whether a file in ``src/`` is a source to keep in sync (not build output)."""
    return path.suffix not in _GENERATED_SUFFIXES and path.name not in _GENERATED_NAMES


def _copy_if_changed(source: pathlib.Path, dest: pathlib.Path) -> bool:
    """Copy ``source`` onto ``dest`` unless they already match in size and mtime."""
    if dest.exists():
        src_stat, dest_stat = source.stat(), dest.stat()
        if (
            src_stat.st_size == dest_stat.st_size
            and src_stat.st_mtime_ns == dest_stat.st_mtime_ns
        ):
            return False
    dest.parent.mkdir(parents=True, exist_ok=True)
    shutil.copy2(source, dest)
    return True


def materialize_build_tree(
    lbm_path: pathlib.Path,
    build_root: pathlib.Path,
) -> pathlib.Path:
    """
    Mirror the LBM sources into a private build tree and return its root.

    The mirror is incremental: only files that differ from the submodule in size
    or mtime are copied, so repeated runs cost a stat per source file. Files the
    wrapper generates into the copy (``mod_dimensions.F90`` and the geometry case
    in ``m_solid_objects_init.F90``) are restored from the submodule on every
    call and immediately regenerated by ``set_experiment`` /
    ``update_solid_objects_init``, which keeps the copy from accumulating edits
    that no longer match the config.

    Args:
        lbm_path: Root of the LBM submodule checkout (contains ``src/``, ``bin/``).
        build_root: Directory to materialize the private tree into.

    Returns:
        ``build_root``, containing ``src/`` and ``bin/``.

    Raises:
        FileNotFoundError: If ``lbm_path/src`` does not exist.
    """
    source_src = lbm_path / "src"
    if not source_src.is_dir():
        raise FileNotFoundError(
            f"LBM sources not found at {source_src}. The submodule at {lbm_path} "
            "is missing or empty -- run 'git submodule update --init --recursive'."
        )

    dest_src = build_root / "src"
    dest_src.mkdir(parents=True, exist_ok=True)
    (build_root / "build").mkdir(parents=True, exist_ok=True)

    mirrored: set[str] = set()
    copied = 0
    for source_file in sorted(source_src.iterdir()):
        if not source_file.is_file() or not _is_mirrored(source_file):
            continue
        mirrored.add(source_file.name)
        if _copy_if_changed(source_file, dest_src / source_file.name):
            copied += 1

    # Drop sources that vanished upstream. Leaving one behind is not harmless:
    # the makefile rebuilds source.files from `ls *.F90`, so a stale module gets
    # compiled back into the binary.
    pruned = 0
    for dest_file in sorted(dest_src.iterdir()):
        if dest_file.is_file() and _is_mirrored(dest_file):
            if dest_file.name not in mirrored:
                dest_file.unlink()
                pruned += 1

    source_bin = lbm_path / "bin"
    if source_bin.is_dir():
        dest_bin = build_root / "bin"
        dest_bin.mkdir(parents=True, exist_ok=True)
        for script in sorted(source_bin.iterdir()):
            if script.is_file() and script.suffix in _BIN_SUFFIXES:
                dest_script = dest_bin / script.name
                if _copy_if_changed(script, dest_script):
                    dest_script.chmod(dest_script.stat().st_mode | 0o111)

    logger.info(
        "LBM build tree at %s (%d file(s) synced, %d pruned, source %s)",
        build_root,
        copied,
        pruned,
        lbm_path,
    )
    return build_root


def resolve_build_root(
    lbm_path: pathlib.Path,
    temp_dir: pathlib.Path,
    isolated: bool,
) -> pathlib.Path:
    """
    Decide where the build tree lives and make sure it is populated.

    Args:
        lbm_path: Root of the LBM checkout.
        temp_dir: The run's scratch directory (``paths.experiment_dir``).
        isolated: True when ``PYLBM_LBM_PATH`` already points at a private tree,
            in which case it is built in place and nothing is mirrored.

    Returns:
        The root of the tree to build in.
    """
    if isolated:
        return lbm_path

    override = os.environ.get("PYLBM_BUILD_ROOT")
    build_root = (
        pathlib.Path(override).expanduser().resolve()
        if override
        else pathlib.Path(temp_dir).resolve() / "lbm_build"
    )
    return materialize_build_tree(lbm_path=lbm_path, build_root=build_root)


def build_stamp_path(build_root: pathlib.Path) -> pathlib.Path:
    """Path of the stamp describing what the binary in this tree was built from."""
    return build_root / "bin" / BUILD_STAMP_NAME


def compute_build_signature(
    src_path: pathlib.Path,
    experiment_name: str,
    enable_cuda: Union[bool, str],
    enable_netcdf: bool,
) -> dict[str, Any]:
    """
    Describe the inputs that are baked into the compiled binary.

    ``mod_dimensions.F90`` carries the grid dimensions and
    ``m_solid_objects_init.F90`` the geometry case, both of which are compiled in.
    Hashing their contents catches a binary built for a different grid or a
    different experiment -- which otherwise produces wrong-shaped or all-NaN
    output with no error at all.

    ``enable_cuda`` is recorded for diagnostics only and is deliberately *not*
    part of the staleness check: it changes neither the numerics nor the array
    shapes, and ``cuda="auto"`` legitimately resolves differently per host.
    """
    digests: dict[str, str] = {}
    for name in ("mod_dimensions.F90", "m_solid_objects_init.F90"):
        candidate = src_path / name
        if candidate.exists():
            digests[name] = hashlib.sha256(candidate.read_bytes()).hexdigest()[:16]
    return {
        "experiment": experiment_name,
        "cuda": enable_cuda if isinstance(enable_cuda, bool) else str(enable_cuda),
        "netcdf": bool(enable_netcdf),
        "sources": digests,
    }


def write_build_stamp(
    build_root: pathlib.Path,
    signature: dict[str, Any],
) -> None:
    """Record what the binary now in ``build_root/bin`` was built from."""
    stamp = build_stamp_path(build_root)
    stamp.parent.mkdir(parents=True, exist_ok=True)
    stamp.write_text(json.dumps(signature, indent=2, sort_keys=True))


def read_build_stamp(build_root: pathlib.Path) -> Optional[dict[str, Any]]:
    """Read the build stamp, or None when it is missing or unreadable."""
    stamp = build_stamp_path(build_root)
    if not stamp.exists():
        return None
    try:
        loaded = json.loads(stamp.read_text())
    except (OSError, ValueError):
        return None
    return loaded if isinstance(loaded, dict) else None
